### ISSUE TITLE
closer view and cockpit view

### ISSUE THREAD

**Issue by yoel123** [yoel123/godot-yoel-space-sim-game#26]
what the title says for the player ship.

and a button to change between these views.

**Comment by exocetfalling** [comment]
![image](https://user-images.githubusercontent.com/70193215/228443850-75a0075b-a5c5-4104-837b-4bcd9c28a659.png)
WIP.

**Comment by exocetfalling** [comment]
![image](https://user-images.githubusercontent.com/70193215/228444443-a9c2d027-e9a2-4264-a3ec-5493c118f7d7.png)
Cockpit view, we need to hide external model in this view.
